# Generated by Django 4.1.5 on 2023-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sname", models.CharField(max_length=50)),
                ("Semail", models.EmailField(max_length=254)),
                ("Spassword", models.CharField(max_length=50)),
                ("Saddress", models.TextField()),
            ],
        ),
    ]
